/*
Xander Rouse
103590876
*/


/*
ORGANISATION (ORGID, ORGANISATIONNAME)
PRIMARY KEY (ORGID)

CLIENT (CLIENTID, NAME, PHONE)
PRIMARY KEY (CLIENTID)

MENUITEM (ITEMID, DESCRIPTION, SERVESPERUNIT, UNITPRICE)
PRIMARY KEY (ITEMID)

ORDER (CLIENTID, DATETIMEPLACED, DELIVERYADDRESS)
PRIMARY KEY (CLIENTID, DATETIMEPLACED)
FOREIGN KEY (CLIENTID) REFERENCES CLIENT

ORDERLINE (CLIENTID, DATETIMEPLACED, ITEMID, QTY)
PRIMARY KEY (CLIENTID, DATETIMEPLACE, ITEMID)
FOREIGN KEY (CLIENTID) REFERENCES CLIENT
FOREIGN KEY (DATETIMEPLACED) REFERENCES ORDER
FOREIGN KEY (ITEMID) REFERENCES MENUITEM
*/

