/*
Xander Rouse
103590876
*/


/*
ORGANISATION (ORGID, ORGANISATIONNAME)
PRIMARY KEY (ORGID)

CLIENT (CLIENTID, NAME, PHONE)
PRIMARY KEY (CLIENTID)

MENUITEM (ITEMID, DESCRIPTION, SERVESPERUNIT, UNITPRICE)
PRIMARY KEY (ITEMID)

ORDER (CLIENTID, DATETIMEPLACED, DELIVERYADDRESS)
PRIMARY KEY (CLIENTID, DATETIMEPLACED)
FOREIGN KEY (CLIENTID) REFERENCES CLIENT

ORDERLINE (CLIENTID, DATETIMEPLACED, ITEMID, QTY)
PRIMARY KEY (CLIENTID, DATETIMEPLACED, ITEMID)
FOREIGN KEY (CLIENTID) REFERENCES CLIENT
FOREIGN KEY (DATETIMEPLACED) REFERENCES ORDER
FOREIGN KEY (ITEMID) REFERENCES MENUITEM
*/

DROP TABLE IF EXISTS ORDERLINE, "ORDER", MENUITEM, CLIENT, ORGANISATION;

CREATE TABLE "ORGANISATION" (
"ORGID" NVARCHAR(4), 
"ORGANISATIONNAME" NVARCHAR(200) NOT NULL UNIQUE,
PRIMARY KEY (ORGID))

CREATE TABLE "CLIENT" (
    "CLIENTID" INT, 
    "NAME" NVARCHAR(100) NOT NULL, 
    "PHONE" NVARCHAR(15) NOT NULL UNIQUE,
PRIMARY KEY (CLIENTID),
);

CREATE TABLE "MENUITEM" (
    "ITEMID" INT, 
    "DESCRIPTION" NVARCHAR(100) NOT NULL UNIQUE, 
    "SERVESPERUNIT" INT NOT NULL, 
    "UNITPRICE" MONEY NOT NULL,
PRIMARY KEY (ITEMID))

CREATE TABLE "ORDER" (
    "CLIENTID" INT, 
    "DATETIMEPLACED" DATE, 
    "DELIVERYADDRESS" NVARCHAR (MAX),
PRIMARY KEY (CLIENTID, DATETIMEPLACED),
FOREIGN KEY (CLIENTID) REFERENCES CLIENT)

GO

CREATE TABLE ORDERLINE (
    "CLIENTID" INT, 
    "DATETIMEPLACED" DATE, 
    "ITEMID" INT, 
    "QTY" INT NOT NULL,
PRIMARY KEY (CLIENTID, DATETIMEPLACED, ITEMID),
FOREIGN KEY (CLIENTID, DATETIMEPLACED) REFERENCES "ORDER"(CLIENTID, DATETIMEPLACED),
FOREIGN KEY (ITEMID) REFERENCES MENUITEM,
CONSTRAINT QTY_LEGNTH CHECK( LEN(QTY)>0))
